name: easyroute  # Nome do seu app
description: Um app para navegação e rotas personalizadas.  # Descrição
version: 1.0.0+1  # Versão (formato: versão+build)

environment:
  sdk: '>=3.0.0 <4.0.0'  # Versão do Dart/Flutter

dependencies:
  flutter:
    sdk: flutter
  google_maps_flutter: ^2.5.0
  
  # Pacote para manipulação de localização
  location: ^5.0.3
  
  # Pacote para manipulação de imagens
  image_picker: ^1.0.4
  
  # Pacote para permissões
  permission_handler: ^11.0.0

  # Pacote para ícones
  cupertino_icons: ^1.0.2


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
  - C:\Users\1319360\Desktop\flutter_application_1\build\assets\download.jpg